### ISSUE TITLE
Use Import-Module to install xSQLServer

### ISSUE THREAD

**Issue by guitarrapc** [MasayukiOzawa/SQLServer-Util#1]
It's better using `Install-Module xSQLServer -Scope AllUsers` for PowerShell v5 and higher hosts.

https://github.com/MasayukiOzawa/SQLServer-Util/blob/master/PowerShell/DSC/Install-SQLServer.ps1#L1-L2

This will not work for WMF v4 or lower but it would be enough to let other's notify HOW TO and practice at once.

**Comment by MasayukiOzawa** [comment]
Thank you!!
It was added to the comment in the file.
